version: '3.9'

services:
  postgres_demo:
    container_name: postgres_demo
    image: postgres:alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6424
      PGDATA: /data/postgres
    volumes:
       - postgres-db-volume:/data/postgres
    ports:
      - "5433:5432"

volumes:
  postgres-db-volume: